export const GET_USER_BY_ID = "GET_USER_BY_ID"
export const GET_USER_BY_ID_BEGIN = "GET_USER_BY_ID_BEGIN"
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS"
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL"

export const GET_USERS = "GET_USERS"
export const GET_USERS_BEGIN = "GET_USERS_BEGIN"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const ADD_USER = "ADD_USER"
export const ADD_USER_BEGIN = "ADD_USER_BEGIN"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USERS_FAIL"

export const EDIT_USER_BY_ID = "EDIT_USER_BY_ID"
export const EDIT_USER_BY_ID_BEGIN = "EDIT_USER_BY_ID_BEGIN"
export const EDIT_USER_BY_ID_SUCCESS = "EDIT_USER_BY_ID_SUCCESS"
export const EDIT_USER_BY_ID_FAIL = "EDIT_USER_BY_ID_FAIL"

export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID"
export const DELETE_USER_BY_ID_BEGIN = "DELETE_USER_BY_ID_BEGIN"
export const DELETE_USER_BY_ID_SUCCESS = "DELETE_USER_BY_ID_SUCCESS"
export const DELETE_USER_BY_ID_FAIL = "DELETE_USER_BY_ID_FAIL"